"name": |-
  Run tests
"on":
  "push":
    "branches":
    - |-
      main
  "pull_request":
    "branches":
    - |-
      main
  "workflow_dispatch":
"jobs":
  "test":
    "runs-on": |-
      ubuntu-latest
    "steps":
    - "name": |-
        Checkout
      "uses": |-
        actions/checkout@v3
    - "name": |-
        Set up Python
      "uses": |-
        actions/setup-python@v4
      "with":
        "python-version": |-
          3.11.1
    - "name": |-
        poetry cache
      "uses": |-
        actions/cache@v3
      "with":
        "path": |-
          ~/.cache/pypoetry
        "key": |-
          ${{ runner.os }}-poetry
    - "name": |-
        pre-commit-cache
      "uses": |-
        actions/cache@v3
      "with":
        "path": |-
          ~/.cache/pre-commit
        "key": |-
          ${{ runner.os }}-venv-${{ hashFiles('.pre-commit-config.yaml') }}
    - "name": |-
        Set up the environment
      "run": |
        pip install -U pip
        pip install poetry>=1.1.11
        poetry install
    - "name": |-
        Run pre-commit hooks
      "run": |
        poetry run pre-commit install
        poetry run pre-commit run --all-files
    - "name": |-
        Run Tests
      "run": |-
        make test-coverage
